### PR TITLE
Fix drawing glitches, cursor and drag&drop handling

### PR DESCRIPTION
**Pull request by X547**

### CODE REVIEW

**Comment by diversys** [comment]
@waddlesplash @pulkomandy could you review this please?

**Comment by waddlesplash** [comment]
I really don't know much about this code... I think I trust @X547 enough to assume he knows what he is doing here and just merge it anyway, but, it would probably be better if someone who knows a little more takes a look?

**Comment by X547** [comment]
I found some regressions caused by this patch:
1. Text become broken if dragging selection and immediately dropping. Undo recover text.
2. Pe window bring to front when hover tool bar buttons.

I fix this later.

**Comment by X547** [comment]
Also there are some glitches still present such as selected line bottom 1px line sometimes not painted.

**Comment by X547** [comment]
Pe window activation when tooltip window is displayed seems to be haiku bug. Pe tooltip use B_FLOATING_APP_WINDOW_FEEL window feel and Haiku tooltip use private `kMenuWindowFeel` window feel. Changing window feel to kMenuWindowFeel solves problem.

**Comment by diversys** [comment]
Ready to merge?

**Comment by pulkomandy** [comment]
I also have no idea and I don't use Pe. @X547, do you want direct commit access here? If you plan to work more on it, that is probably easier.

**Pull request merged**
