### PR TITLE
fixed issue #7 (FTP login problems)

### PR DESCRIPTION
**Pull request by hannahyp**
Screenshots of some of the new error messages:

incorrect login

failed to connect

### CODE REVIEW

**Comment by pulkomandy** [comment]
Would it be possible to mark the host field (with BTextView->MarkAsInvalid) in these cases?

In the default case, maybe it would be better to use strerror() to get a slightly more specific error message?

**Comment by mmuman** [comment]
Well for login/password you can't be sure which of the 2 fields is invalid though, you could mark both I suppose.

**Comment by mmuman** [comment]
Hmm actually the issue seems to be fixed already in the current trunk... at least using a bad login does fail and let you change it.

**Comment by hannahyp** [comment]
Part 2 of issue #7 only occurs when the ftp host doesn't exist. When the host exists but username/password is invalid, the connect() function does not fail, i.e., it doesn't return a negative int value.

**Comment by hannahyp** [comment]
I will try to mark the host field with BTextView->MarkAsInvalid and use strerror() for the default case.

**Comment by hannahyp** [comment]
I think that among the 7 values returned by the connect() function, only ECONNREFUSED (the listener rejected the connection), ETIMEDOUT (the connection attempt timed out), and ENETUNREACH (the client can't get to the network) are of interest to the user. I propose two alternatives below:
alternatives
(I prefer the 2nd one.)

**Comment by hannahyp** [comment]
BTextView (or TextView) doesn't have MarkAsInvalid as a member or function. How should I mark the host field?

**Comment by hannahyp** [comment]
This code:
code
shows this when the ftp host doesn't exist:
bad hostname

**Comment by mmuman** [comment]
Looks weird, connect() shouldn't give this error.

**Comment by mmuman** [comment]
Anyway, I think the2nd solution is better as it gives more info.

**Comment by hannahyp** [comment]
I had noticed it, too. It seems that connect() has a bug in returning error code.

**Comment by hannahyp** [comment]
Then I will use the above code, which is an improvement to alternative #2. I will mark the host field if you know how.

**Comment by mmuman** [comment]
Well, HTextControl is a BTextControl, not a BTextView, and BTextControl is a BControl which does have MarkAsInvalid(bool). So it should work. Of course it means also resetting the invalid state when the control content changes to not leave it marked.

**Comment by hannahyp** [comment]
Thanks! fServerName->MarkAsInvalid(true) woks. I don't know how to tell if an HTextControl's content has changed. Where can I find documentation or sample code?

**Comment by mmuman** [comment]
Here is the documentation for BTextControl: https://api.haiku-os.org/classBTextControl.html
I don't thinkSetText() is called when the text is edited though. Maybe the ModificationMessage is already caught by the FTP dialog, didn't check.

**Comment by hannahyp** [comment]
I don't think using SetText() would work, either. I've played with the KeyDown() function from the Hook Methods group, but KeyDown() doesn't respond to any key presses in the host field.

It seems that I must override KeyDown() of BTextControl by creating one in HTextControl. (I've tried it, but the host field still doesn't respond to the key press events, and thus the field remains marked as invalid.) This would impact many other parts of Pe as HTextControl is used in quite a few places elsewhere.

If there is no easier way to reset the marked host filed, I will skip it for now and just fix the 2nd bug (part 2) of issue #7. Please let me know your thoughts.

**Comment by pulkomandy** [comment]
As françois mentionned, you can use SetModificationMessage to tell the TextControl that it should send a message when it is modified. Then, in MessageReceived, you can receive the message, and make a decision.

An example control doing this:
http://cgit.haiku-os.org/haiku/tree/src/preferences/network/IPAddressControl.cpp

(it processes the message itself, but you can process it in another class, depending what SetTarget() was set to for the control).

**Comment by hannahyp** [comment]
Hi Adrien, thanks for the tip! I got it to work.

**Comment by mmuman** [comment]
Overriding KeyDown on a BTextControl won't work, because it's the BTextView it contains which has the focus and receives key presses.

**Comment by hannahyp** [comment]
Thanks for the explanation! I will study the GUI API when I have time.

**Comment by scottmc** [comment]
What's the status on this issue?

**Comment by hannahyp** [comment]
I think it can be closed.

**Pull request closed without merging**
